In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('fraudTrain.csv')

In [3]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [4]:
label_encoder = LabelEncoder()
df['trans_date_trans_time'] = label_encoder.fit_transform(df['trans_date_trans_time'])
df['merchant'] = label_encoder.fit_transform(df['merchant'])
df['category'] = label_encoder.fit_transform(df['category'])
df['job'] = label_encoder.fit_transform(df['job'])
df['dob'] = label_encoder.fit_transform(df['dob'])
df['trans_num'] = label_encoder.fit_transform(df['trans_num'])
df['unix_time'] = label_encoder.fit_transform(df['unix_time'])
df['first'] = label_encoder.fit_transform(df['first'])
df['last'] = label_encoder.fit_transform(df['last'])
df['gender'] = label_encoder.fit_transform(df['gender'])
df['street'] = label_encoder.fit_transform(df['street'])
df['city'] = label_encoder.fit_transform(df['city'])
df['state'] = label_encoder.fit_transform(df['state'])

In [5]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,0,2703186189652095,514,8,4.97,162,18,0,568,...,36.0788,-81.1781,3495,370,779,56438,0,36.011293,-82.048315,0
1,1,1,630423337322,241,4,107.23,309,157,0,435,...,48.8878,-118.2105,149,428,607,159395,1,49.159047,-118.186462,0
2,2,2,38859492057661,390,0,220.11,115,381,1,602,...,42.1808,-112.2620,4154,307,302,818703,2,43.150704,-112.154481,0
3,3,3,3534093764340240,360,2,45.00,163,463,1,930,...,46.2306,-112.1138,1939,328,397,544575,3,47.034331,-112.561071,0
4,4,4,375534208663984,297,9,41.96,336,149,1,418,...,38.4207,-79.4629,99,116,734,831111,4,38.674999,-78.632459,0

In [6]:
legit = df[df.is_fraud == 0] 
fraud = df[df.is_fraud == 1]

In [7]:
print(legit.shape)

(1289169, 23)

In [8]:
print(fraud.shape)

(7506, 23)

In [9]:
legit_sample = legit.sample(7506)

In [10]:
new_df = pd.concat([legit_sample,fraud])

In [11]:
new_df['is_fraud'].value_counts()

is_fraud
0    7506
1    7506
Name: count, dtype: int64

In [12]:
X = new_df.drop(columns = 'is_fraud',axis=1)
y = new_df['is_fraud']

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3 , random_state = 1)

In [14]:
dtc = DecisionTreeClassifier()

In [15]:
dtc.fit(X_train,y_train)

DecisionTreeClassifier()

In [16]:
dtc.predict(X_test)

array([1, 1, 0, ..., 0, 1, 1], dtype=int64)

In [17]:
dtc.score(X_test,y_test)

0.9553730017761989

In [18]:
df_test = pd.read_csv('fraudTest.csv')
df_test['trans_date_trans_time'] = label_encoder.fit_transform(df_test['trans_date_trans_time'])
df_test['merchant'] = label_encoder.fit_transform(df_test['merchant'])
df_test['category'] = label_encoder.fit_transform(df_test['category'])
df_test['job'] = label_encoder.fit_transform(df_test['job'])
df_test['dob'] = label_encoder.fit_transform(df_test['dob'])
df_test['trans_num'] = label_encoder.fit_transform(df_test['trans_num'])
df_test['unix_time'] = label_encoder.fit_transform(df_test['unix_time'])
df_test['first'] = label_encoder.fit_transform(df_test['first'])
df_test['last'] = label_encoder.fit_transform(df_test['last'])
df_test['gender'] = label_encoder.fit_transform(df_test['gender'])
df_test['street'] = label_encoder.fit_transform(df_test['street'])
df_test['city'] = label_encoder.fit_transform(df_test['city'])
df_test['state'] = label_encoder.fit_transform(df_test['state'])

In [19]:
df_test

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,0,2291163933867244,319,10,2.86,151,115,1,341,...,33.9659,-80.9355,333497,275,376,98699,0,33.986391,-81.200714,0
1,1,1,3573030041201292,591,10,29.84,163,457,0,354,...,40.3207,-110.4360,302,392,760,108785,1,39.450498,-109.960431,0
2,2,2,3598215285024754,611,5,41.28,24,249,0,865,...,40.6729,-73.5365,34496,259,421,433979,2,40.495810,-74.196111,0
3,3,3,3591919803438423,222,9,60.05,42,457,1,320,...,28.5697,-80.8191,54767,407,718,71993,3,28.812398,-80.883061,0
4,4,4,3526826139003047,292,13,3.19,247,261,1,548,...,44.2529,-85.0170,1126,196,177,190585,4,44.959148,-85.884734,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555714,555714,544755,30560609640617,507,5,43.77,235,315,1,531,...,40.4931,-91.8912,519,460,334,336391,544755,39.946837,-91.333331,0
555715,555715,544756,3556613125071656,264,7,111.84,171,424,1,540,...,29.0393,-95.4401,28739,198,890,70372,544756,29.661049,-96.186633,0
555716,555716,544757,6011724471098086,496,7,86.88,18,239,0,126,...,46.1966,-118.9017,3684,294,609,235088,544757,46.658340,-119.715054,0
555717,555717,544758,4079773899158,75,13,7.99,111,342,1,663,...,44.6255,-116.4493,129,58,331,43546,544758,44.470525,-117.080888,0
555718,555718,544759,4170689372027579,125,0,38.13,280,145,1,778,...,35.6665,-97.4798,116001,276,813,50595,544759,36.210097,-97.036372,0

In [20]:
X = df_test.drop(columns='is_fraud',axis=1)
y = df_test['is_fraud']

In [21]:
pred = dtc.predict(X)
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [22]:
dtc.score(X,y)

0.9464819450117775